### ISSUE TITLE
 to determine which pairs of points from either cloud correspond

### ISSUE THREAD

**Issue by ChenShengsGitHub** [jewettaij/superpose3d#2]
This function does not attempt to determine which pairs of points from either cloud correspond. Instead, it infers them from the order of the arrays.
I wonder if there exisits methods that determine which pairs of points from either cloud correspond, if true, could you please give me a link?

**Comment by jewettaij** [comment]
Hi Chen Sheng
   In the context of bioinformatics, yes.  When comparing the shapes of two proteins, people are sometimes trying to infer (from their shapes) which amino acids from either protein were probably inherited from a common ancestor.  So they superimpose the two protein structures and pick nearby pairs of points (one from either protein).  I wrote [one of these algorithms](http://www.rbvi.ucsf.edu/Research/projects/minrms/), although the [source code hosted there](http://www.rbvi.ucsf.edu/Research/projects/minrms/minrms.tar.gz) no longer compiles with modern compilers.  (I no longer work there but I can email anyone with updated code.)  Since then, at least one or two newer algorithms have been published which may perform better on some kinds of proteins.  All of these protein-structure-comparison algorithms that I know of exploit the assumption that the cloud of points is ordered (one point per amino acid), and successive points (amino acids) from one protein are always matched with successive amino acids from the other protein (since insertion or deletion mutations preserve the order of the remaining amino acids).  This makes it possible to perform an exhaustive, optimal search for matches.

In the more general case, there are several approaches, like ICP which work on general 3D point clouds (without ordering).  If my understanding is correct, these algorithms are not exhaustive or deterministic, and they are not guaranteed to pick the optimal pairs of points from either cloud.  But they aim to do a reasonably good job.  I am not an expert on this topic, but after a quick google search, I noticed a few links which might be helpful:

https://en.wikipedia.org/wiki/Point_set_registration
https://en.wikipedia.org/wiki/Iterative_closest_point
https://arxiv.org/abs/2001.07715

I hope this is not too late to be useful.
-Andrew

**Comment by ChenShengsGitHub** [comment]
Thank you very much!

Andrew Jewett ***@***.***> 于2021年9月14日周二 上午2:07写道：

**Comment by jewettaij** [comment]
Another github user has posted an answer to this question:
https://github.com/jewettaij/superpose3d/issues/5

I'll go ahead and close this issue.
